[build]

command = "npm run build && npm run export"
publish = "out/"

# Redirect from soulprovider.fm to soulprovidr.fm.
[[redirects]]
from = "https://soulprovider.fm/*"
to = "https://soulprovidr.fm/:splat"
status = 301
force = true