[build]

command = "npm run build --no-lint"
publish = ".next/"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect from soulprovider.fm to soulprovidr.fm.
[[redirects]]
from = "https://soulprovider.fm/*"
to = "https://soulprovidr.fm/:splat"
status = 301
force = true