[build]

command = "npm run build"
publish = "public/"

# Redirect from soulprovider.fm to soulprovidr.fm.
[[redirects]]
from = "https://soulprovider.fm/*"
to = "https://soulprovidr.fm/:splat"
status = 301
force = true